//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ar.com.bbva.web.services.usrdtws.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UsrsDataExceptionCodeDescrip_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar/xsd", "codeDescrip");
    private final static QName _UsrsDataExceptionErrCause_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar/xsd", "errCause");
    private final static QName _UsrsDataExceptionAddInfo_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar/xsd", "addInfo");
    private final static QName _UsrsDataExceptionErrMsg_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar/xsd", "errMsg");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ar.com.bbva.web.services.usrdtws.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UsrsDataException }
     * 
     */
    public UsrsDataException createUsrsDataException() {
        return new UsrsDataException();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", name = "codeDescrip", scope = UsrsDataException.class)
    public JAXBElement<String> createUsrsDataExceptionCodeDescrip(String value) {
        return new JAXBElement<String>(_UsrsDataExceptionCodeDescrip_QNAME, String.class, UsrsDataException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", name = "errCause", scope = UsrsDataException.class)
    public JAXBElement<String> createUsrsDataExceptionErrCause(String value) {
        return new JAXBElement<String>(_UsrsDataExceptionErrCause_QNAME, String.class, UsrsDataException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", name = "addInfo", scope = UsrsDataException.class)
    public JAXBElement<String> createUsrsDataExceptionAddInfo(String value) {
        return new JAXBElement<String>(_UsrsDataExceptionAddInfo_QNAME, String.class, UsrsDataException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", name = "errMsg", scope = UsrsDataException.class)
    public JAXBElement<String> createUsrsDataExceptionErrMsg(String value) {
        return new JAXBElement<String>(_UsrsDataExceptionErrMsg_QNAME, String.class, UsrsDataException.class, value);
    }

}
