//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UsrsDataException complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsrsDataException">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="codeDescrip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errCause" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsrsDataException", namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", propOrder = {
    "addInfo",
    "code",
    "codeDescrip",
    "errCause",
    "errMsg"
})
public class UsrsDataException {

    @XmlElementRef(name = "addInfo", namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", type = JAXBElement.class)
    protected JAXBElement<String> addInfo;
    protected Integer code;
    @XmlElementRef(name = "codeDescrip", namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", type = JAXBElement.class)
    protected JAXBElement<String> codeDescrip;
    @XmlElementRef(name = "errCause", namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", type = JAXBElement.class)
    protected JAXBElement<String> errCause;
    @XmlElementRef(name = "errMsg", namespace = "http://usrdtws.services.web.bbva.com.ar/xsd", type = JAXBElement.class)
    protected JAXBElement<String> errMsg;

    /**
     * Gets the value of the addInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAddInfo() {
        return addInfo;
    }

    /**
     * Sets the value of the addInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAddInfo(JAXBElement<String> value) {
        this.addInfo = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCode(Integer value) {
        this.code = value;
    }

    /**
     * Gets the value of the codeDescrip property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCodeDescrip() {
        return codeDescrip;
    }

    /**
     * Sets the value of the codeDescrip property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodeDescrip(JAXBElement<String> value) {
        this.codeDescrip = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the errCause property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getErrCause() {
        return errCause;
    }

    /**
     * Sets the value of the errCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setErrCause(JAXBElement<String> value) {
        this.errCause = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the errMsg property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getErrMsg() {
        return errMsg;
    }

    /**
     * Sets the value of the errMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setErrMsg(JAXBElement<String> value) {
        this.errMsg = ((JAXBElement<String> ) value);
    }

}
