log4j.rootCategory=info, Default, LOG_CONSOLA
log4j.appender.Default=org.apache.log4j.DailyRollingFileAppender
log4j.appender.LOG_CONSOLA=org.apache.log4j.ConsoleAppender
#log4j.appender.Default=org.apache.log4j.ConsoleAppender
log4j.appender.Default.Threshold=info
log4j.appender.Default.ImmediateFlush=true
log4j.appender.Default.append=true
log4j.appender.Default.DatePattern='.'yyyy-MM-dd
log4j.appender.Default.layout=org.apache.log4j.PatternLayout
log4j.appender.Default.layout.ConversionPattern=%d %-5p ===> %c - %m%n
log4j.appender.Default.File=C:/Users/A127216/eclipse-workspace/BBVA/SUMINISTROS/Suministros/log/Suministros.log

log4j.appender.LOG_CONSOLA.Threshold=info
log4j.appender.LOG_CONSOLA.ImmediateFlush=true
log4j.appender.LOG_CONSOLA.append=true
log4j.appender.LOG_CONSOLA.DatePattern='.'yyyy-MM-dd
log4j.appender.LOG_CONSOLA.layout=org.apache.log4j.PatternLayout
log4j.appender.LOG_CONSOLA.layout.ConversionPattern=%d %-5p ===> %c - %m%n



# Print only messages of level WARN or above
log4j.logger.javax.faces=WARN
log4j.logger.org.apache.myfaces=WARN
log4j.logger.com.sun.faces=WARN

# logs the SQL statements
#log4j.logger.org.hibernate.SQL=debug 

# Logs the JDBC parameters passed to a query
#log4j.logger.org.hibernate.type=trace 


log4j.org.hibernate=info
log4j.org.hibernate.SQL=info
log4j.org.hibernate.type.descriptor.sql=trace
log4j.org.hibernate.type.descriptor.sql.BasicBinder=trace
log4j.org.hibernate.type.descriptor.sql.BasicExtractor=info
log4j.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=fatal
log4j.ar.com.bbva=trace
log4j.ar.com.itrsa.sam=info
log4j.org.apache.commons.beanutils=info
log4j.org.apache.commons.digester=info
log4j.org.apache.commons.httpclient=info
log4j.org.ehcache=info

#    <Logger name="ar.com.bbva" level="trace" />
#    <Logger name="com.zaxxer.hikari" level="info" />
#    <Logger name="ar.com.itrsa.sam" level="info" />
#    <Logger name="net.sf.ehcache" level="info" />
#    <Logger name="org.apache.axiom" level="info" />
#    <Logger name="org.apache.axis2" level="info" />
#    <Logger name="org.apache.commons.beanutils" level="info" />
#    <Logger name="org.apache.commons.digester" level="info" />
#    <Logger name="org.apache.commons.httpclient" level="info" />
#    <Logger name="org.ehcache" level="info" />

