# Properties de configuracion

# WebService userDataws
userDataws.url=http://was70aacc1/UsersData/services/userDataws

# Base de datos Oracle
jdbc.driverClassName=oracle.jdbc.pool.OracleDataSource
jdbc.url=jdbc:oracle:thin:@localhost:55001:ORCLCDB
jdbc.username=LDRSUMINISTROS
jdbc.password=suministros2018
hibernate.dialect=org.hibernate.dialect.OracleDialect

hibernate.show_sql=true
# Properties de configuracion
# WebService userDataws
#userDataws.url=http://was70aacc1/UsersData/services/userDataws

#hibernate.show_sql=true
hibernate.format_sql=true

# Batchs
batch.update.UsuarioCentroCostos.schedule=0 0 23 * * MON-FRI
batch.update.UsuarioCentroCostos.file.path=C:\\Users\\usuario\\Desktop\\Sistemas Activos\\suministros
#batch.update.UsuarioCentroCostos.file.path=C:\\Users\\lmur\\Desktop\\eclipse-jee-oxygen-M2-win32-x86_64\\workspace\\bbva\\Suministros
batch.update.UsuarioCentroCostos.file.name=update_Usuario_Centro_Costos

#BatchCC
batch.pendiente.Procesar.schedule=0 10 15 * * MON-FRI