--------------------------------------------------------
-- Archivo creado  - viernes-octubre-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_ID_SOLICITUD
--------------------------------------------------------

   CREATE SEQUENCE  "OPERACIONES"."SEQUENCE_ID_SOLICITUD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 29 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_INTERFAZ_CONTABLE
--------------------------------------------------------

   CREATE SEQUENCE  "OPERACIONES"."SEQUENCE_INTERFAZ_CONTABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_INTERFAZ_OPERATIVA
--------------------------------------------------------

   CREATE SEQUENCE  "OPERACIONES"."SEQUENCE_INTERFAZ_OPERATIVA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_OPERACION
--------------------------------------------------------

   CREATE SEQUENCE  "OPERACIONES"."SEQUENCE_OPERACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ARCHIVO_SOL
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."ARCHIVO_SOL" 
   (	"COD_ARCHIVO" CHAR(36 CHAR), 
	"COD_SOLICITUD" CHAR(36 CHAR), 
	"ID_REPO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(75 CHAR), 
	"TIPO" VARCHAR2(60 CHAR), 
	"FECHA_HORA" TIMESTAMP (6), 
	"TAMANO" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASIENTO_CONTABLE
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."ASIENTO_CONTABLE" 
   (	"SECUENCIAL_INTERFAZ_CONTABLE" NUMBER(10,0), 
	"SECUENCIAL_OPERACION" NUMBER(10,0), 
	"RISTRA" VARCHAR2(80 CHAR), 
	"NRO_OPERACION" NUMBER(10,0), 
	"CODIGO_MONEDA" CHAR(3 CHAR), 
	"IMPORTE" NUMBER(13,2), 
	"FECHA_CONTABLE" DATE, 
	"CCOSTO_ORIGEN" CHAR(4 CHAR), 
	"CODIGO_DETALLE" CHAR(36 CHAR), 
	"CODIGO_OPERACION" CHAR(4 CHAR), 
	"CCOSTO_DESTINO" CHAR(4 CHAR), 
	"ESTADO" CHAR(1 CHAR), 
	"FECHA_ALTA" DATE, 
	"USUARIO_DE_APROBADOR" CHAR(8 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASIENTO_OPERATIVO
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."ASIENTO_OPERATIVO" 
   (	"SECUENCIAL_INTERFAZ_OPERATIVA" NUMBER(10,0), 
	"SECUENCIAL_OPERACION" NUMBER(10,0), 
	"USUARIO_DE_ALTA_OPERACION" CHAR(8 CHAR), 
	"CODIGO_MONEDA" CHAR(3 CHAR), 
	"IMPORTE_MONEDA_ORIGEN" NUMBER(18,2), 
	"CBU" VARCHAR2(22 CHAR), 
	"COTIZACION_MONEDA" NUMBER(9,4), 
	"IMPORTE_MONEDA_LOCAL" NUMBER(18,2), 
	"NRO_OPERACION" NUMBER(10,0), 
	"CLAVE_CONCEPTO" CHAR(3 CHAR), 
	"CODIGO_OPERACION" CHAR(4 CHAR), 
	"ESTADO" CHAR(1 CHAR), 
	"FECHA_ALTA" DATE, 
	"USUARIO_DE_APROBADOR" CHAR(8 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUDITORIA
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."AUDITORIA" 
   (	"COD_AUDITORIA" CHAR(36 CHAR), 
	"ACCION" VARCHAR2(10 CHAR), 
	"ENTIDAD" VARCHAR2(20 CHAR), 
	"COD_OPERACION" CHAR(36 CHAR), 
	"COD_SOLICITUD" CHAR(36 CHAR), 
	"USUARIO" VARCHAR2(15 CHAR), 
	"FECHA_HORA" TIMESTAMP (6), 
	"DATOS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DESTINATARIO_OP
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."DESTINATARIO_OP" 
   (	"COD_DESTINATARIO" CHAR(36 CHAR), 
	"COD_OPERACION" CHAR(36 CHAR), 
	"RAZON_SOCIAL" VARCHAR2(100 CHAR), 
	"CUIT" NUMBER(*,0), 
	"CBU" VARCHAR2(22 CHAR), 
	"COD_SOLICITUD" CHAR(36 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_OP
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."DETALLE_OP" 
   (	"COD_DETALLE_OP" CHAR(36 CHAR), 
	"CODIGO" CHAR(4 CHAR), 
	"COD_OPERACION" CHAR(36 CHAR), 
	"COD_SOLICITUD" CHAR(36 CHAR), 
	"DESCRIPCION" VARCHAR2(15 CHAR), 
	"OBLIGATORIO" CHAR(1 BYTE), 
	"CC_DISTRIBUCION_ORIGEN" CHAR(1 CHAR), 
	"CC_DISTRIBUCION" CHAR(4 CHAR), 
	"RISTRA" VARCHAR2(80 CHAR), 
	"APLICA_NRO_DOC" CHAR(1 BYTE), 
	"USUARIO_CREACION" VARCHAR2(15 CHAR), 
	"ELIMINADO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_SOL
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."DETALLE_SOL" 
   (	"COD_DETALLE_SOL" CHAR(36 CHAR), 
	"COD_SOLICITUD" CHAR(36 CHAR), 
	"COD_DETALLE_OP" CHAR(36 CHAR), 
	"CC_DISTRIBUCION" CHAR(4 CHAR), 
	"MONTO" NUMBER(18,2), 
	"NRO_DOC" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DISTRIBUCION_OP
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."DISTRIBUCION_OP" 
   (	"COD_DISTRIBUCION" CHAR(36 CHAR), 
	"COD_DETALLE_OP" CHAR(36 CHAR), 
	"CC_DISTRIBUCION" CHAR(4 CHAR), 
	"CC_DESTINO" CHAR(4 CHAR), 
	"PORCENTAJE" NUMBER(18,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DISTRIBUCION_SOL
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."DISTRIBUCION_SOL" 
   (	"COD_DISTRIBUCION_SOL" CHAR(36 CHAR), 
	"COD_DETALLE_SOL" CHAR(36 CHAR), 
	"CC_DESTINO" CHAR(4 CHAR), 
	"PORCENTAJE" NUMBER(18,2), 
	"MONTO" NUMBER(18,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MONEDA
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."MONEDA" 
   (	"COD_MONEDA" CHAR(3 CHAR), 
	"DESCRIPCION" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OPERACION
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."OPERACION" 
   (	"COD_OPERACION" CHAR(36 CHAR), 
	"CODIGO" CHAR(4 CHAR), 
	"DESCRIPCION" VARCHAR2(15 CHAR), 
	"OPERATIVO" CHAR(3 CHAR), 
	"CC_CONTABLE_ORIGEN" CHAR(1 CHAR), 
	"CC_CONTABLE" CHAR(4 CHAR), 
	"DIAS_CONTABLES" NUMBER(*,0), 
	"COD_MONEDA" CHAR(3 CHAR), 
	"VALIDO_HASTA" DATE, 
	"NRO_DOC" VARCHAR2(20 CHAR), 
	"ESTADO" VARCHAR2(12 CHAR), 
	"CLAVE_CONCEPTO" CHAR(3 CHAR), 
	"ACREDITACION_INMEDIATA" CHAR(1 BYTE) DEFAULT 'N', 
	"ELIMINADO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OWNER_OP
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."OWNER_OP" 
   (	"COD_OWNER" CHAR(36 CHAR), 
	"COD_OPERACION" CHAR(36 CHAR), 
	"COD_ROL" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."ROL" 
   (	"COD_ROL" VARCHAR2(10 CHAR), 
	"DESCRIPCION" VARCHAR2(60 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOLICITUD
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."SOLICITUD" 
   (	"COD_SOLICITUD" CHAR(36 CHAR), 
	"ID_SOLICITUD" NUMBER(10,0), 
	"COD_OPERACION" CHAR(36 CHAR), 
	"ESTADO" CHAR(2 CHAR), 
	"FECHA_CONTABLE" DATE, 
	"COD_MONEDA" CHAR(3 CHAR), 
	"MONTO" NUMBER(18,2), 
	"COTIZACION" NUMBER(5,2), 
	"DETALLE" VARCHAR2(4000 CHAR), 
	"CENTRO_COSTO" CHAR(4 CHAR), 
	"COD_DESTINATARIO" CHAR(36 CHAR), 
	"FACTURA_NRO" VARCHAR2(20 CHAR), 
	"FACTURA_FECHA" DATE, 
	"CAE_CAI" NUMBER(*,0), 
	"SOLICITANTE" VARCHAR2(15 CHAR), 
	"SOLICITANTE_NOMBRE" VARCHAR2(100 CHAR), 
	"OWNER" VARCHAR2(15 CHAR), 
	"OWNER_NOMBRE" VARCHAR2(100 CHAR), 
	"PAGADOR" VARCHAR2(15 CHAR), 
	"PAGADOR_NOMBRE" VARCHAR2(100 CHAR), 
	"FECHA_ALTA" DATE, 
	"ELIMINADO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."USUARIO" 
   (	"ID_USR" CHAR(8 CHAR), 
	"ID_CENTR_COS" CHAR(4 CHAR), 
	"ID_SECTOR" CHAR(4 CHAR), 
	"NOM_APELL" VARCHAR2(75 CHAR), 
	"FE_ALTA" DATE, 
	"ID_NIVEL" CHAR(2 CHAR), 
	"NRO_CTA_MON" NUMBER(15,2), 
	"ID_MAIL" VARCHAR2(200 CHAR), 
	"FE_ULT_MOD" TIMESTAMP (6), 
	"USR_ULT_MOD" CHAR(8 CHAR), 
	"TERM_ULT_MOD" CHAR(4 CHAR), 
	"NRO_LEGAJO" CHAR(8 CHAR), 
	"FE_BAJA" DATE, 
	"ID_CENTR_CTB" CHAR(4 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VALIDACION_OP
--------------------------------------------------------

  CREATE TABLE "OPERACIONES"."VALIDACION_OP" 
   (	"COD_VALIDACION" CHAR(36 CHAR), 
	"COD_OPERACION" CHAR(36 CHAR), 
	"COD_DETALLE_OP" CHAR(36 CHAR), 
	"COD_SOLICITUD" CHAR(36 CHAR), 
	"MONTO" NUMBER(18,2), 
	"PERIODO" CHAR(1 CHAR), 
	"LIMITE_CC" CHAR(1 CHAR), 
	"VALIDO_HASTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into OPERACIONES.ARCHIVO_SOL
SET DEFINE OFF;
REM INSERTING into OPERACIONES.ASIENTO_CONTABLE
SET DEFINE OFF;
REM INSERTING into OPERACIONES.ASIENTO_OPERATIVO
SET DEFINE OFF;
REM INSERTING into OPERACIONES.AUDITORIA
SET DEFINE OFF;
REM INSERTING into OPERACIONES.DESTINATARIO_OP
SET DEFINE OFF;
REM INSERTING into OPERACIONES.DETALLE_OP
SET DEFINE OFF;
REM INSERTING into OPERACIONES.DETALLE_SOL
SET DEFINE OFF;
REM INSERTING into OPERACIONES.DISTRIBUCION_OP
SET DEFINE OFF;
REM INSERTING into OPERACIONES.DISTRIBUCION_SOL
SET DEFINE OFF;
REM INSERTING into OPERACIONES.MONEDA
SET DEFINE OFF;
Insert into OPERACIONES.MONEDA (COD_MONEDA,DESCRIPCION) values ('ARS','PESOS');
commit;
REM INSERTING into OPERACIONES.OPERACION
SET DEFINE OFF;
REM INSERTING into OPERACIONES.OWNER_OP
SET DEFINE OFF;
REM INSERTING into OPERACIONES.ROL
SET DEFINE OFF;
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG04','ADM INMUEBLES');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG07','RECURSOS HUMANOS');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG13','PUBLICIDAD');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG05','MEDIOS');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG03','GABINETE');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG14','REL. LABORALES');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG15','SERV. JURIDICOS');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG25','REL. INSTITUCIONALES');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG41','DEPTO MEDICO');
Insert into OPERACIONES.ROL (COD_ROL,DESCRIPCION) values ('GLG17','IMPUESTOS');
commit;
REM INSERTING into OPERACIONES.SOLICITUD
SET DEFINE OFF;
REM INSERTING into OPERACIONES.USUARIO
SET DEFINE OFF;
Insert into OPERACIONES.USUARIO (ID_USR,ID_CENTR_COS,ID_SECTOR,NOM_APELL,FE_ALTA,ID_NIVEL,NRO_CTA_MON,ID_MAIL,FE_ULT_MOD,USR_ULT_MOD,TERM_ULT_MOD,NRO_LEGAJO,FE_BAJA,ID_CENTR_CTB) values ('PAGADOR1','1111',null,null,null,null,null,null,to_timestamp('23/09/2020 06:03:55,892000000 PM','DD/MM/RRRR HH12:MI:SSXFF AM'),'1111    ','1111','PAGADOR1',null,'1111');
Insert into OPERACIONES.USUARIO (ID_USR,ID_CENTR_COS,ID_SECTOR,NOM_APELL,FE_ALTA,ID_NIVEL,NRO_CTA_MON,ID_MAIL,FE_ULT_MOD,USR_ULT_MOD,TERM_ULT_MOD,NRO_LEGAJO,FE_BAJA,ID_CENTR_CTB) values ('PAGADOR2','2222',null,null,null,null,null,null,to_timestamp('23/09/2020 06:03:55,892000000 PM','DD/MM/RRRR HH12:MI:SSXFF AM'),'1111    ','1111','PAGADOR2',null,'2222');
Insert into OPERACIONES.USUARIO (ID_USR,ID_CENTR_COS,ID_SECTOR,NOM_APELL,FE_ALTA,ID_NIVEL,NRO_CTA_MON,ID_MAIL,FE_ULT_MOD,USR_ULT_MOD,TERM_ULT_MOD,NRO_LEGAJO,FE_BAJA,ID_CENTR_CTB) values ('PAGADOR3','3333',null,null,null,null,null,null,to_timestamp('23/09/2020 06:03:55,892000000 PM','DD/MM/RRRR HH12:MI:SSXFF AM'),'1111    ','1111','PAGADOR3',null,'3333');
Insert into OPERACIONES.USUARIO (ID_USR,ID_CENTR_COS,ID_SECTOR,NOM_APELL,FE_ALTA,ID_NIVEL,NRO_CTA_MON,ID_MAIL,FE_ULT_MOD,USR_ULT_MOD,TERM_ULT_MOD,NRO_LEGAJO,FE_BAJA,ID_CENTR_CTB) values ('OWNER111','1111',null,null,null,null,null,null,to_timestamp('23/09/2020 06:03:55,892000000 PM','DD/MM/RRRR HH12:MI:SSXFF AM'),'1111    ','1111','OWNER111',null,'1111');
Insert into OPERACIONES.USUARIO (ID_USR,ID_CENTR_COS,ID_SECTOR,NOM_APELL,FE_ALTA,ID_NIVEL,NRO_CTA_MON,ID_MAIL,FE_ULT_MOD,USR_ULT_MOD,TERM_ULT_MOD,NRO_LEGAJO,FE_BAJA,ID_CENTR_CTB) values ('OWNER222','2222',null,null,null,null,null,null,to_timestamp('23/09/2020 06:03:55,892000000 PM','DD/MM/RRRR HH12:MI:SSXFF AM'),'1111    ','1111','OWNER222',null,'2222');
Insert into OPERACIONES.USUARIO (ID_USR,ID_CENTR_COS,ID_SECTOR,NOM_APELL,FE_ALTA,ID_NIVEL,NRO_CTA_MON,ID_MAIL,FE_ULT_MOD,USR_ULT_MOD,TERM_ULT_MOD,NRO_LEGAJO,FE_BAJA,ID_CENTR_CTB) values ('REQUEST1','1111',null,null,null,null,null,null,to_timestamp('23/09/2020 06:03:55,892000000 PM','DD/MM/RRRR HH12:MI:SSXFF AM'),'1111    ','1111','REQUEST1',null,'1111');
Insert into OPERACIONES.USUARIO (ID_USR,ID_CENTR_COS,ID_SECTOR,NOM_APELL,FE_ALTA,ID_NIVEL,NRO_CTA_MON,ID_MAIL,FE_ULT_MOD,USR_ULT_MOD,TERM_ULT_MOD,NRO_LEGAJO,FE_BAJA,ID_CENTR_CTB) values ('REQUEST2','2222',null,null,null,null,null,null,to_timestamp('23/09/2020 06:03:55,892000000 PM','DD/MM/RRRR HH12:MI:SSXFF AM'),'1111    ','1111','REQUEST2',null,'2222');
commit;
REM INSERTING into OPERACIONES.VALIDACION_OP
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ARCHIVO_SOL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."ARCHIVO_SOL_PK" ON "OPERACIONES"."ARCHIVO_SOL" ("COD_ARCHIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ASIENTO_CONTABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."ASIENTO_CONTABLE_PK" ON "OPERACIONES"."ASIENTO_CONTABLE" ("CODIGO_DETALLE", "SECUENCIAL_INTERFAZ_CONTABLE", "SECUENCIAL_OPERACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ASIENTO_OPERATIVO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."ASIENTO_OPERATIVO_PK" ON "OPERACIONES"."ASIENTO_OPERATIVO" ("SECUENCIAL_INTERFAZ_OPERATIVA", "SECUENCIAL_OPERACION", "NRO_OPERACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUDITORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."AUDITORIA_PK" ON "OPERACIONES"."AUDITORIA" ("COD_AUDITORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CENTRO_COSTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."CENTRO_COSTOS_PK" ON "OPERACIONES"."USUARIO" ("ID_USR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DESTINATARIO_OP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."DESTINATARIO_OP_PK" ON "OPERACIONES"."DESTINATARIO_OP" ("COD_DESTINATARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_OP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."DETALLE_OP_PK" ON "OPERACIONES"."DETALLE_OP" ("COD_DETALLE_OP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_SOL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."DETALLE_SOL_PK" ON "OPERACIONES"."DETALLE_SOL" ("COD_DETALLE_SOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DISTRIBUCION_OP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."DISTRIBUCION_OP_PK" ON "OPERACIONES"."DISTRIBUCION_OP" ("COD_DISTRIBUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DISTRIBUCION_SOL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."DISTRIBUCION_SOL_PK" ON "OPERACIONES"."DISTRIBUCION_SOL" ("COD_DISTRIBUCION_SOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACULTAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."FACULTAD_PK" ON "OPERACIONES"."ROL" ("COD_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MONEDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."MONEDA_PK" ON "OPERACIONES"."MONEDA" ("COD_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OPERACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."OPERACION_PK" ON "OPERACIONES"."OPERACION" ("COD_OPERACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OWNER_OP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."OWNER_OP_PK" ON "OPERACIONES"."OWNER_OP" ("COD_OWNER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOLICITUD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."SOLICITUD_PK" ON "OPERACIONES"."SOLICITUD" ("COD_SOLICITUD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VALIDACION_OP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."VALIDACION_OP_PK" ON "OPERACIONES"."VALIDACION_OP" ("COD_VALIDACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLE_OP__COD
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."DETALLE_OP__COD" ON "OPERACIONES"."DETALLE_OP" ("CODIGO", "COD_SOLICITUD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NRO_DOC
--------------------------------------------------------

  CREATE INDEX "OPERACIONES"."NRO_DOC" ON "OPERACIONES"."DETALLE_SOL" ("NRO_DOC" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LEGAJO
--------------------------------------------------------

  CREATE INDEX "OPERACIONES"."LEGAJO" ON "OPERACIONES"."USUARIO" ("NRO_LEGAJO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUDITORIA__IDXV1
--------------------------------------------------------

  CREATE INDEX "OPERACIONES"."AUDITORIA__IDXV1" ON "OPERACIONES"."AUDITORIA" ("COD_OPERACION", "COD_SOLICITUD", "USUARIO", "FECHA_HORA", "ACCION", "ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATE
--------------------------------------------------------

  CREATE INDEX "OPERACIONES"."STATE" ON "OPERACIONES"."OPERACION" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OPERACION__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPERACIONES"."OPERACION__IDX" ON "OPERACIONES"."OPERACION" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DETALLE_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DETALLE_OP" MODIFY ("COD_DETALLE_OP" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_OP" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_OP" MODIFY ("COD_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_OP" MODIFY ("APLICA_NRO_DOC" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_OP" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_OP" ADD CONSTRAINT "DETALLE_OP_PK" PRIMARY KEY ("COD_DETALLE_OP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUDITORIA
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."AUDITORIA" MODIFY ("COD_AUDITORIA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."AUDITORIA" ADD CONSTRAINT "AUDITORIA_PK" PRIMARY KEY ("COD_AUDITORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRIBUCION_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DISTRIBUCION_OP" MODIFY ("COD_DISTRIBUCION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_OP" MODIFY ("COD_DETALLE_OP" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_OP" MODIFY ("CC_DISTRIBUCION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_OP" MODIFY ("CC_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_OP" MODIFY ("PORCENTAJE" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_OP" ADD CONSTRAINT "DISTRIBUCION_OP_PK" PRIMARY KEY ("COD_DISTRIBUCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MONEDA
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."MONEDA" MODIFY ("COD_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."MONEDA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."MONEDA" ADD CONSTRAINT "MONEDA_PK" PRIMARY KEY ("COD_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OWNER_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."OWNER_OP" MODIFY ("COD_OWNER" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OWNER_OP" MODIFY ("COD_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OWNER_OP" MODIFY ("COD_ROL" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OWNER_OP" ADD CONSTRAINT "OWNER_OP_PK" PRIMARY KEY ("COD_OWNER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASIENTO_CONTABLE
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("SECUENCIAL_INTERFAZ_CONTABLE" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("SECUENCIAL_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("RISTRA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("NRO_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("CODIGO_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("IMPORTE" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("FECHA_CONTABLE" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("CCOSTO_ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("CODIGO_DETALLE" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("CODIGO_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("CCOSTO_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("FECHA_ALTA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" MODIFY ("USUARIO_DE_APROBADOR" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_CONTABLE" ADD CONSTRAINT "ASIENTO_CONTABLE_PK" PRIMARY KEY ("CODIGO_DETALLE", "SECUENCIAL_INTERFAZ_CONTABLE", "SECUENCIAL_OPERACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASIENTO_OPERATIVO
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("SECUENCIAL_INTERFAZ_OPERATIVA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("SECUENCIAL_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("USUARIO_DE_ALTA_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("CODIGO_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("IMPORTE_MONEDA_ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("CBU" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("COTIZACION_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("IMPORTE_MONEDA_LOCAL" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("NRO_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("CLAVE_CONCEPTO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("CODIGO_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("FECHA_ALTA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" MODIFY ("USUARIO_DE_APROBADOR" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ASIENTO_OPERATIVO" ADD CONSTRAINT "ASIENTO_OPERATIVO_PK" PRIMARY KEY ("SECUENCIAL_INTERFAZ_OPERATIVA", "SECUENCIAL_OPERACION", "NRO_OPERACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISTRIBUCION_SOL
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DISTRIBUCION_SOL" MODIFY ("COD_DISTRIBUCION_SOL" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_SOL" MODIFY ("COD_DETALLE_SOL" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_SOL" MODIFY ("CC_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_SOL" MODIFY ("PORCENTAJE" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_SOL" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DISTRIBUCION_SOL" ADD CONSTRAINT "DISTRIBUCION_SOL_PK" PRIMARY KEY ("COD_DISTRIBUCION_SOL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPERACION
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("COD_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("CC_CONTABLE_ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("DIAS_CONTABLES" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("COD_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("NRO_DOC" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("CLAVE_CONCEPTO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("ACREDITACION_INMEDIATA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."OPERACION" ADD CONSTRAINT "OPERACION_PK" PRIMARY KEY ("COD_OPERACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."ROL" MODIFY ("COD_ROL" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ROL" ADD CONSTRAINT "FACULTAD_PK" PRIMARY KEY ("COD_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DESTINATARIO_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DESTINATARIO_OP" MODIFY ("COD_DESTINATARIO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DESTINATARIO_OP" MODIFY ("RAZON_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DESTINATARIO_OP" MODIFY ("CUIT" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DESTINATARIO_OP" MODIFY ("CBU" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DESTINATARIO_OP" ADD CONSTRAINT "DESTINATARIO_OP_PK" PRIMARY KEY ("COD_DESTINATARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_SOL
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DETALLE_SOL" MODIFY ("COD_DETALLE_SOL" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_SOL" MODIFY ("COD_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_SOL" MODIFY ("COD_DETALLE_OP" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."DETALLE_SOL" ADD CONSTRAINT "DETALLE_SOL_PK" PRIMARY KEY ("COD_DETALLE_SOL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOLICITUD
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."SOLICITUD" MODIFY ("COD_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."SOLICITUD" MODIFY ("ID_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."SOLICITUD" MODIFY ("COD_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."SOLICITUD" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."SOLICITUD" MODIFY ("FECHA_ALTA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."SOLICITUD" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."SOLICITUD" ADD CONSTRAINT "SOLICITUD_PK" PRIMARY KEY ("COD_SOLICITUD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VALIDACION_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."VALIDACION_OP" MODIFY ("COD_VALIDACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" MODIFY ("COD_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" MODIFY ("COD_DETALLE_OP" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" MODIFY ("LIMITE_CC" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" ADD CONSTRAINT "VALIDACION_OP_PK" PRIMARY KEY ("COD_VALIDACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARCHIVO_SOL
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" MODIFY ("COD_ARCHIVO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" MODIFY ("COD_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" MODIFY ("ID_REPO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" MODIFY ("TAMANO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" ADD CONSTRAINT "ARCHIVO_SOL_PK" PRIMARY KEY ("COD_ARCHIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."USUARIO" MODIFY ("ID_USR" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."USUARIO" MODIFY ("FE_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."USUARIO" MODIFY ("USR_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."USUARIO" MODIFY ("TERM_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."USUARIO" MODIFY ("NRO_LEGAJO" NOT NULL ENABLE);
  ALTER TABLE "OPERACIONES"."USUARIO" ADD CONSTRAINT "CENTRO_COSTOS_PK" PRIMARY KEY ("ID_USR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARCHIVO_SOL
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."ARCHIVO_SOL" ADD CONSTRAINT "IMAGENES_SOL_SOLICITUD_FK" FOREIGN KEY ("COD_SOLICITUD")
	  REFERENCES "OPERACIONES"."SOLICITUD" ("COD_SOLICITUD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DESTINATARIO_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DESTINATARIO_OP" ADD CONSTRAINT "DESTINATARIO_OP_OPERACION_FK" FOREIGN KEY ("COD_OPERACION")
	  REFERENCES "OPERACIONES"."OPERACION" ("COD_OPERACION") ENABLE;
  ALTER TABLE "OPERACIONES"."DESTINATARIO_OP" ADD CONSTRAINT "DESTINATARIO_OP_SOLICITUD_FK" FOREIGN KEY ("COD_SOLICITUD")
	  REFERENCES "OPERACIONES"."SOLICITUD" ("COD_SOLICITUD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DETALLE_OP" ADD CONSTRAINT "DETALLE_OP_OPERACION_FK" FOREIGN KEY ("COD_OPERACION")
	  REFERENCES "OPERACIONES"."OPERACION" ("COD_OPERACION") ENABLE;
  ALTER TABLE "OPERACIONES"."DETALLE_OP" ADD CONSTRAINT "DETALLE_OP_SOLICITUD_FK" FOREIGN KEY ("COD_SOLICITUD")
	  REFERENCES "OPERACIONES"."SOLICITUD" ("COD_SOLICITUD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_SOL
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DETALLE_SOL" ADD CONSTRAINT "DETALLE_SOL_DETALLE_OP_FK" FOREIGN KEY ("COD_DETALLE_OP")
	  REFERENCES "OPERACIONES"."DETALLE_OP" ("COD_DETALLE_OP") ENABLE;
  ALTER TABLE "OPERACIONES"."DETALLE_SOL" ADD CONSTRAINT "DETALLE_SOL_SOLICITUD_FK" FOREIGN KEY ("COD_SOLICITUD")
	  REFERENCES "OPERACIONES"."SOLICITUD" ("COD_SOLICITUD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISTRIBUCION_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DISTRIBUCION_OP" ADD CONSTRAINT "DISTRIBUCION_OP_DETALLE_OP_FK" FOREIGN KEY ("COD_DETALLE_OP")
	  REFERENCES "OPERACIONES"."DETALLE_OP" ("COD_DETALLE_OP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISTRIBUCION_SOL
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."DISTRIBUCION_SOL" ADD CONSTRAINT "DIS_SOL_DETALLE_SOL_FK" FOREIGN KEY ("COD_DETALLE_SOL")
	  REFERENCES "OPERACIONES"."DETALLE_SOL" ("COD_DETALLE_SOL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPERACION
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."OPERACION" ADD CONSTRAINT "OPERACION_MONEDA_FK" FOREIGN KEY ("COD_MONEDA")
	  REFERENCES "OPERACIONES"."MONEDA" ("COD_MONEDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OWNER_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."OWNER_OP" ADD CONSTRAINT "OWNER_OP_OPERACION_FK" FOREIGN KEY ("COD_OPERACION")
	  REFERENCES "OPERACIONES"."OPERACION" ("COD_OPERACION") ENABLE;
  ALTER TABLE "OPERACIONES"."OWNER_OP" ADD CONSTRAINT "OWNER_OP_ROL_FK" FOREIGN KEY ("COD_ROL")
	  REFERENCES "OPERACIONES"."ROL" ("COD_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOLICITUD
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."SOLICITUD" ADD CONSTRAINT "SOLICITUD_DESTINATARIO_OP_FK" FOREIGN KEY ("COD_DESTINATARIO")
	  REFERENCES "OPERACIONES"."DESTINATARIO_OP" ("COD_DESTINATARIO") ENABLE;
  ALTER TABLE "OPERACIONES"."SOLICITUD" ADD CONSTRAINT "SOLICITUD_MONEDA_FK" FOREIGN KEY ("COD_MONEDA")
	  REFERENCES "OPERACIONES"."MONEDA" ("COD_MONEDA") ENABLE;
  ALTER TABLE "OPERACIONES"."SOLICITUD" ADD CONSTRAINT "SOLICITUD_OPERACION_FK" FOREIGN KEY ("COD_OPERACION")
	  REFERENCES "OPERACIONES"."OPERACION" ("COD_OPERACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VALIDACION_OP
--------------------------------------------------------

  ALTER TABLE "OPERACIONES"."VALIDACION_OP" ADD CONSTRAINT "VALIDACION_OP_DETALLE_OP_FK" FOREIGN KEY ("COD_DETALLE_OP")
	  REFERENCES "OPERACIONES"."DETALLE_OP" ("COD_DETALLE_OP") ENABLE;
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" ADD CONSTRAINT "VALIDACION_OP_OPERACION_FK" FOREIGN KEY ("COD_OPERACION")
	  REFERENCES "OPERACIONES"."OPERACION" ("COD_OPERACION") ENABLE;
  ALTER TABLE "OPERACIONES"."VALIDACION_OP" ADD CONSTRAINT "VALIDACION_OP_SOLICITUD_FK" FOREIGN KEY ("COD_SOLICITUD")
	  REFERENCES "OPERACIONES"."SOLICITUD" ("COD_SOLICITUD") ENABLE;
--------------------------------------------------------
--  DDL for Trigger SOLICITUD_ID_SOLICITUD_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "OPERACIONES"."SOLICITUD_ID_SOLICITUD_TRG" BEFORE
    INSERT ON solicitud
    FOR EACH ROW
     WHEN ( new.id_solicitud IS NULL ) BEGIN
    :new.id_solicitud := sequence_id_solicitud.nextval;
END;
/
ALTER TRIGGER "OPERACIONES"."SOLICITUD_ID_SOLICITUD_TRG" ENABLE;
