//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ar.com.bbva.web.services.usrdtws.xsd.UsrsDataException;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ar.com.bbva.web.services.usrdtws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UsersMailsGroupGroupName_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "groupName");
    private final static QName _UsersMailsGroupArea_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "area");
    private final static QName _GroupsAppAltmrCdApp_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "altmrCdApp");
    private final static QName _GroupsAppSegInfCdApp_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "segInfCdApp");
    private final static QName _UserRolesLegajo_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "legajo");
    private final static QName _UserDatawsUsrsDataExceptionUsrsDataException_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "UsrsDataException");
    private final static QName _UsersMailsRoleRoleName_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "roleName");
    private final static QName _MembersGroupOutType_QNAME = new QName("http://usrdtws.services.web.bbva.com.ar", "outType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ar.com.bbva.web.services.usrdtws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserGroupsResponse }
     * 
     */
    public UserGroupsResponse createUserGroupsResponse() {
        return new UserGroupsResponse();
    }

    /**
     * Create an instance of {@link UsersMailsGroup }
     * 
     */
    public UsersMailsGroup createUsersMailsGroup() {
        return new UsersMailsGroup();
    }

    /**
     * Create an instance of {@link GroupsApp }
     * 
     */
    public GroupsApp createGroupsApp() {
        return new GroupsApp();
    }

    /**
     * Create an instance of {@link UsersMailsResponse }
     * 
     */
    public UsersMailsResponse createUsersMailsResponse() {
        return new UsersMailsResponse();
    }

    /**
     * Create an instance of {@link UsersIdentif }
     * 
     */
    public UsersIdentif createUsersIdentif() {
        return new UsersIdentif();
    }

    /**
     * Create an instance of {@link UserRoles }
     * 
     */
    public UserRoles createUserRoles() {
        return new UserRoles();
    }

    /**
     * Create an instance of {@link FacsAppResponse }
     * 
     */
    public FacsAppResponse createFacsAppResponse() {
        return new FacsAppResponse();
    }

    /**
     * Create an instance of {@link UserDatawsUsrsDataException }
     * 
     */
    public UserDatawsUsrsDataException createUserDatawsUsrsDataException() {
        return new UserDatawsUsrsDataException();
    }

    /**
     * Create an instance of {@link FacsApp }
     * 
     */
    public FacsApp createFacsApp() {
        return new FacsApp();
    }

    /**
     * Create an instance of {@link MembersRole }
     * 
     */
    public MembersRole createMembersRole() {
        return new MembersRole();
    }

    /**
     * Create an instance of {@link UserDataResponse }
     * 
     */
    public UserDataResponse createUserDataResponse() {
        return new UserDataResponse();
    }

    /**
     * Create an instance of {@link UserData }
     * 
     */
    public UserData createUserData() {
        return new UserData();
    }

    /**
     * Create an instance of {@link AppsInfoResponse }
     * 
     */
    public AppsInfoResponse createAppsInfoResponse() {
        return new AppsInfoResponse();
    }

    /**
     * Create an instance of {@link UsersMailsRoleResponse }
     * 
     */
    public UsersMailsRoleResponse createUsersMailsRoleResponse() {
        return new UsersMailsRoleResponse();
    }

    /**
     * Create an instance of {@link UserGroups }
     * 
     */
    public UserGroups createUserGroups() {
        return new UserGroups();
    }

    /**
     * Create an instance of {@link UsersIdentifResponse }
     * 
     */
    public UsersIdentifResponse createUsersIdentifResponse() {
        return new UsersIdentifResponse();
    }

    /**
     * Create an instance of {@link MembersRoleResponse }
     * 
     */
    public MembersRoleResponse createMembersRoleResponse() {
        return new MembersRoleResponse();
    }

    /**
     * Create an instance of {@link MembersGroupResponse }
     * 
     */
    public MembersGroupResponse createMembersGroupResponse() {
        return new MembersGroupResponse();
    }

    /**
     * Create an instance of {@link AppsInfo }
     * 
     */
    public AppsInfo createAppsInfo() {
        return new AppsInfo();
    }

    /**
     * Create an instance of {@link UserRolesResponse }
     * 
     */
    public UserRolesResponse createUserRolesResponse() {
        return new UserRolesResponse();
    }

    /**
     * Create an instance of {@link GroupsAppResponse }
     * 
     */
    public GroupsAppResponse createGroupsAppResponse() {
        return new GroupsAppResponse();
    }

    /**
     * Create an instance of {@link UsersMailsGroupResponse }
     * 
     */
    public UsersMailsGroupResponse createUsersMailsGroupResponse() {
        return new UsersMailsGroupResponse();
    }

    /**
     * Create an instance of {@link UsersMailsRole }
     * 
     */
    public UsersMailsRole createUsersMailsRole() {
        return new UsersMailsRole();
    }

    /**
     * Create an instance of {@link MembersGroup }
     * 
     */
    public MembersGroup createMembersGroup() {
        return new MembersGroup();
    }

    /**
     * Create an instance of {@link UsersMails }
     * 
     */
    public UsersMails createUsersMails() {
        return new UsersMails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "groupName", scope = UsersMailsGroup.class)
    public JAXBElement<String> createUsersMailsGroupGroupName(String value) {
        return new JAXBElement<String>(_UsersMailsGroupGroupName_QNAME, String.class, UsersMailsGroup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "area", scope = UsersMailsGroup.class)
    public JAXBElement<String> createUsersMailsGroupArea(String value) {
        return new JAXBElement<String>(_UsersMailsGroupArea_QNAME, String.class, UsersMailsGroup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "altmrCdApp", scope = GroupsApp.class)
    public JAXBElement<String> createGroupsAppAltmrCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppAltmrCdApp_QNAME, String.class, GroupsApp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "segInfCdApp", scope = GroupsApp.class)
    public JAXBElement<String> createGroupsAppSegInfCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppSegInfCdApp_QNAME, String.class, GroupsApp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "segInfCdApp", scope = AppsInfo.class)
    public JAXBElement<String> createAppsInfoSegInfCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppSegInfCdApp_QNAME, String.class, AppsInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "segInfCdApp", scope = UserRoles.class)
    public JAXBElement<String> createUserRolesSegInfCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppSegInfCdApp_QNAME, String.class, UserRoles.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "legajo", scope = UserRoles.class)
    public JAXBElement<String> createUserRolesLegajo(String value) {
        return new JAXBElement<String>(_UserRolesLegajo_QNAME, String.class, UserRoles.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsrsDataException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "UsrsDataException", scope = UserDatawsUsrsDataException.class)
    public JAXBElement<UsrsDataException> createUserDatawsUsrsDataExceptionUsrsDataException(UsrsDataException value) {
        return new JAXBElement<UsrsDataException>(_UserDatawsUsrsDataExceptionUsrsDataException_QNAME, UsrsDataException.class, UserDatawsUsrsDataException.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "roleName", scope = UsersMailsRole.class)
    public JAXBElement<String> createUsersMailsRoleRoleName(String value) {
        return new JAXBElement<String>(_UsersMailsRoleRoleName_QNAME, String.class, UsersMailsRole.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "area", scope = UsersMailsRole.class)
    public JAXBElement<String> createUsersMailsRoleArea(String value) {
        return new JAXBElement<String>(_UsersMailsGroupArea_QNAME, String.class, UsersMailsRole.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "segInfCdApp", scope = MembersGroup.class)
    public JAXBElement<String> createMembersGroupSegInfCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppSegInfCdApp_QNAME, String.class, MembersGroup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "outType", scope = MembersGroup.class)
    public JAXBElement<String> createMembersGroupOutType(String value) {
        return new JAXBElement<String>(_MembersGroupOutType_QNAME, String.class, MembersGroup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "groupName", scope = MembersGroup.class)
    public JAXBElement<String> createMembersGroupGroupName(String value) {
        return new JAXBElement<String>(_UsersMailsGroupGroupName_QNAME, String.class, MembersGroup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "segInfCdApp", scope = FacsApp.class)
    public JAXBElement<String> createFacsAppSegInfCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppSegInfCdApp_QNAME, String.class, FacsApp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "segInfCdApp", scope = MembersRole.class)
    public JAXBElement<String> createMembersRoleSegInfCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppSegInfCdApp_QNAME, String.class, MembersRole.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "outType", scope = MembersRole.class)
    public JAXBElement<String> createMembersRoleOutType(String value) {
        return new JAXBElement<String>(_MembersGroupOutType_QNAME, String.class, MembersRole.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "roleName", scope = MembersRole.class)
    public JAXBElement<String> createMembersRoleRoleName(String value) {
        return new JAXBElement<String>(_UsersMailsRoleRoleName_QNAME, String.class, MembersRole.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "legajo", scope = UserData.class)
    public JAXBElement<String> createUserDataLegajo(String value) {
        return new JAXBElement<String>(_UserRolesLegajo_QNAME, String.class, UserData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "segInfCdApp", scope = UserGroups.class)
    public JAXBElement<String> createUserGroupsSegInfCdApp(String value) {
        return new JAXBElement<String>(_GroupsAppSegInfCdApp_QNAME, String.class, UserGroups.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://usrdtws.services.web.bbva.com.ar", name = "legajo", scope = UserGroups.class)
    public JAXBElement<String> createUserGroupsLegajo(String value) {
        return new JAXBElement<String>(_UserRolesLegajo_QNAME, String.class, UserGroups.class, value);
    }

}
