//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

/**
 * userDataws
 * 
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://usrdtws.services.web.bbva.com.ar", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ar.com.bbva.web.services.usrdtws;
