//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws;

import javax.xml.ws.WebFault;

@WebFault(name = "userDatawsUsrsDataException", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
public class UserDatawsUsrsDataException_Exception
    extends Exception
{
	private static final long serialVersionUID = 1L;
	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UserDatawsUsrsDataException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UserDatawsUsrsDataException_Exception(String message, UserDatawsUsrsDataException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public UserDatawsUsrsDataException_Exception(String message, UserDatawsUsrsDataException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ar.com.bbva.web.services.usrdtws.UserDatawsUsrsDataException
     */
    public UserDatawsUsrsDataException getFaultInfo() {
        return faultInfo;
    }

}
