//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "userDataws", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", wsdlLocation = "file:/desa/apps/was/ears/movilidad.ear/userDataws.xml")
public class UserDataws
    extends Service
{

    private final static URL USERDATAWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ar.com.bbva.web.services.usrdtws.UserDataws.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ar.com.bbva.web.services.usrdtws.UserDataws.class.getResource(".");
            url = new URL(baseUrl, "file:/desa/apps/was/ears/movilidad.ear/userDataws.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/desa/apps/was/ears/movilidad.ear/userDataws.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERDATAWS_WSDL_LOCATION = url;
    }

    public UserDataws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserDataws() {
        super(USERDATAWS_WSDL_LOCATION, new QName("http://usrdtws.services.web.bbva.com.ar", "userDataws"));
    }

    /**
     * 
     * @return
     *     returns UserDatawsPortType
     */
    @WebEndpoint(name = "userDatawsHttpSoap11Endpoint")
    public UserDatawsPortType getUserDatawsHttpSoap11Endpoint() {
        return super.getPort(new QName("http://usrdtws.services.web.bbva.com.ar", "userDatawsHttpSoap11Endpoint"), UserDatawsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserDatawsPortType
     */
    @WebEndpoint(name = "userDatawsHttpSoap11Endpoint")
    public UserDatawsPortType getUserDatawsHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://usrdtws.services.web.bbva.com.ar", "userDatawsHttpSoap11Endpoint"), UserDatawsPortType.class, features);
    }

}
