//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry;

@WebService(name = "userDatawsPortType", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
@XmlSeeAlso({
    ar.com.bbva.web.services.usrdtws.xsd.ObjectFactory.class,
    ar.com.bbva.web.services.usrdtws.ldapops.xsd.ObjectFactory.class,
    ar.com.bbva.web.services.usrdtws.ObjectFactory.class
})
public interface UserDatawsPortType {


    /**
     * 
     * @param altmrCdApp
     * @param segInfCdApp
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:groupsApp")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "groupsApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.GroupsApp")
    @ResponseWrapper(localName = "groupsAppResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.GroupsAppResponse")
    public List<LdapWSEntry> groupsApp(
        @WebParam(name = "altmrCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String altmrCdApp,
        @WebParam(name = "segInfCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String segInfCdApp)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param segInfCdApp
     * @param legajo
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:userGroups")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "userGroups", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UserGroups")
    @ResponseWrapper(localName = "userGroupsResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UserGroupsResponse")
    public List<LdapWSEntry> userGroups(
        @WebParam(name = "legajo", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String legajo,
        @WebParam(name = "segInfCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String segInfCdApp)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param legajo
     * @param estructura
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:userData")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "userData", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UserData")
    @ResponseWrapper(localName = "userDataResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UserDataResponse")
    public List<LdapWSEntry> userData(
        @WebParam(name = "legajo", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String legajo,
        @WebParam(name = "estructura", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> estructura)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param segInfCdApp
     * @param legajo
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:userRoles")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "userRoles", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UserRoles")
    @ResponseWrapper(localName = "userRolesResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UserRolesResponse")
    public List<LdapWSEntry> userRoles(
        @WebParam(name = "legajo", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String legajo,
        @WebParam(name = "segInfCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String segInfCdApp)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param legajo
     * @param area
     * @param apellido
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:usersIdentif")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "usersIdentif", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersIdentif")
    @ResponseWrapper(localName = "usersIdentifResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersIdentifResponse")
    public List<LdapWSEntry> usersIdentif(
        @WebParam(name = "apellido", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> apellido,
        @WebParam(name = "legajo", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> legajo,
        @WebParam(name = "area", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> area)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param legajo
     * @param area
     * @param puesto
     * @param apellido
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:usersMails")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "usersMails", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersMails")
    @ResponseWrapper(localName = "usersMailsResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersMailsResponse")
    public List<LdapWSEntry> usersMails(
        @WebParam(name = "apellido", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> apellido,
        @WebParam(name = "legajo", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> legajo,
        @WebParam(name = "area", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> area,
        @WebParam(name = "puesto", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        List<String> puesto)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param segInfCdApp
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:facsApp")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "facsApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.FacsApp")
    @ResponseWrapper(localName = "facsAppResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.FacsAppResponse")
    public List<LdapWSEntry> facsApp(
        @WebParam(name = "segInfCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String segInfCdApp)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param roleName
     * @param area
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:usersMailsRole")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "usersMailsRole", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersMailsRole")
    @ResponseWrapper(localName = "usersMailsRoleResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersMailsRoleResponse")
    public List<LdapWSEntry> usersMailsRole(
        @WebParam(name = "roleName", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String roleName,
        @WebParam(name = "area", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String area)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param groupName
     * @param area
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:usersMailsGroup")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "usersMailsGroup", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersMailsGroup")
    @ResponseWrapper(localName = "usersMailsGroupResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.UsersMailsGroupResponse")
    public List<LdapWSEntry> usersMailsGroup(
        @WebParam(name = "groupName", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String groupName,
        @WebParam(name = "area", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String area)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param roleName
     * @param segInfCdApp
     * @param outType
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:membersRole")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "membersRole", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.MembersRole")
    @ResponseWrapper(localName = "membersRoleResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.MembersRoleResponse")
    public List<LdapWSEntry> membersRole(
        @WebParam(name = "outType", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String outType,
        @WebParam(name = "roleName", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String roleName,
        @WebParam(name = "segInfCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String segInfCdApp)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param segInfCdApp
     * @param outType
     * @param groupName
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:membersGroup")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "membersGroup", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.MembersGroup")
    @ResponseWrapper(localName = "membersGroupResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.MembersGroupResponse")
    public List<LdapWSEntry> membersGroup(
        @WebParam(name = "outType", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String outType,
        @WebParam(name = "groupName", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String groupName,
        @WebParam(name = "segInfCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String segInfCdApp)
        throws UserDatawsUsrsDataException_Exception
    ;

    /**
     * 
     * @param segInfCdApp
     * @return
     *     returns java.util.List<ar.com.bbva.web.services.usrdtws.ldapops.xsd.LdapWSEntry>
     * @throws UserDatawsUsrsDataException_Exception
     */
    @WebMethod(action = "urn:appsInfo")
    @WebResult(targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
    @RequestWrapper(localName = "appsInfo", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.AppsInfo")
    @ResponseWrapper(localName = "appsInfoResponse", targetNamespace = "http://usrdtws.services.web.bbva.com.ar", className = "ar.com.bbva.web.services.usrdtws.AppsInfoResponse")
    public List<LdapWSEntry> appsInfo(
        @WebParam(name = "segInfCdApp", targetNamespace = "http://usrdtws.services.web.bbva.com.ar")
        String segInfCdApp)
        throws UserDatawsUsrsDataException_Exception
    ;

}
