//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ar.com.bbva.web.services.usrdtws.xsd.UsrsDataException;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UsrsDataException" type="{http://usrdtws.services.web.bbva.com.ar/xsd}UsrsDataException" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usrsDataException"
})
@XmlRootElement(name = "userDatawsUsrsDataException")
public class UserDatawsUsrsDataException {

    @XmlElementRef(name = "UsrsDataException", namespace = "http://usrdtws.services.web.bbva.com.ar", type = JAXBElement.class)
    protected JAXBElement<UsrsDataException> usrsDataException;

    /**
     * Gets the value of the usrsDataException property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UsrsDataException }{@code >}
     *     
     */
    public JAXBElement<UsrsDataException> getUsrsDataException() {
        return usrsDataException;
    }

    /**
     * Sets the value of the usrsDataException property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UsrsDataException }{@code >}
     *     
     */
    public void setUsrsDataException(JAXBElement<UsrsDataException> value) {
        this.usrsDataException = ((JAXBElement<UsrsDataException> ) value);
    }

}
