(select TO_CHAR(A.CENTRO_COSTOS_ID,'0000')|| TRIM(B.TIPO_MAT) || TRIM(TO_CHAR(A.NUM_TRATAMIENTO,'00000000')), A.ID,
  A.MATERIAL_ID, substr(B.DESCRIPCION,9,40), TO_CHAR(A.CANT_APROBADA,'0000000'), TO_CHAR(B.UNI_MATERIAL,'0000000'),
  TO_CHAR(A.CENTRO_COSTOS_ID,'0000'),   C.DIRECCION1, C.DIRECCION2, C.DIRECCION3, C.CODPOSTAL,
  TO_CHAR(A.CANT_APROBADA * B.PRECIO_PP,'0000000000.00'), A.FE_ALTA, A.FE_TRATAMIENTO
  from LDRSUMINISTROS.SUM_PEDIDO A,
       LDRSUMINISTROS.SUM_MATERIAL B,
       LDRSUMINISTROS.SUM_CENTRO_COSTOS C
where A.MATERIAL_ID = B.ID
  and A.CENTRO_COSTOS_ID = C.ID 
  and A.NUM_TRATAMIENTO = 14 );