
--------------------------------------------------------
--  DDL for Table SUM_MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" 
   (	"ID" NUMBER(19,0), 
	"FE_ALTA" DATE DEFAULT sysdate, 
	"FE_BAJA" DATE, 
	"FE_MOD" DATE, 
	"USR_ALTA" VARCHAR2(8 BYTE), 
	"USR_BAJA" VARCHAR2(8 BYTE), 
	"USR_MOD" VARCHAR2(8 BYTE), 
	"CANTIDAD" NUMBER(19,0), 
	"CENTRO_COSTOS_ID" NUMBER(19,0), 
	"MATERIAL_ID" NUMBER(19,0), 
	"PRECIO_PP" NUMBER(19,2), 
	"TIPO_MOVIMIENTO" VARCHAR2(20 BYTE)
   )


--------------------------------------------------------
--  DDL for Index SYS_C0012859
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDRSUMINISTROS"."SYS_C0012859" ON "LDRSUMINISTROS"."SUM_MOVIMIENTOS" ("ID");
--------------------------------------------------------
--  Constraints for Table SUM_MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" ADD PRIMARY KEY ("ID");
  ALTER TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" MODIFY ("TIPO_MOVIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" MODIFY ("PRECIO_PP" NOT NULL ENABLE);
  ALTER TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" MODIFY ("CENTRO_COSTOS_ID" NOT NULL ENABLE);
  ALTER TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "LDRSUMINISTROS"."SUM_MOVIMIENTOS" MODIFY ("ID" NOT NULL ENABLE);
  