//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws.ldapops.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LdapWSEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LdapWSEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attribs" type="{http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd}LdapWSPairValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LdapWSEntry", namespace = "http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd", propOrder = {
    "attribs",
    "name"
})
public class LdapWSEntry {

    @XmlElement(nillable = true)
    protected List<LdapWSPairValue> attribs;
    @XmlElementRef(name = "name", namespace = "http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd", type = JAXBElement.class)
    protected JAXBElement<String> name;

    /**
     * Gets the value of the attribs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LdapWSPairValue }
     * 
     * 
     */
    public List<LdapWSPairValue> getAttribs() {
        if (attribs == null) {
            attribs = new ArrayList<LdapWSPairValue>();
        }
        return this.attribs;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = ((JAXBElement<String> ) value);
    }

}
