//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ar.com.bbva.web.services.usrdtws.ldapops.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ar.com.bbva.web.services.usrdtws.ldapops.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LdapWSEntryName_QNAME = new QName("http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd", "name");
    private final static QName _LdapWSPairValueValue_QNAME = new QName("http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ar.com.bbva.web.services.usrdtws.ldapops.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LdapWSEntry }
     * 
     */
    public LdapWSEntry createLdapWSEntry() {
        return new LdapWSEntry();
    }

    /**
     * Create an instance of {@link LdapWSPairValue }
     * 
     */
    public LdapWSPairValue createLdapWSPairValue() {
        return new LdapWSPairValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd", name = "name", scope = LdapWSEntry.class)
    public JAXBElement<String> createLdapWSEntryName(String value) {
        return new JAXBElement<String>(_LdapWSEntryName_QNAME, String.class, LdapWSEntry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd", name = "value", scope = LdapWSPairValue.class)
    public JAXBElement<String> createLdapWSPairValueValue(String value) {
        return new JAXBElement<String>(_LdapWSPairValueValue_QNAME, String.class, LdapWSPairValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ldapOps.usrdtws.services.web.bbva.com.ar/xsd", name = "name", scope = LdapWSPairValue.class)
    public JAXBElement<String> createLdapWSPairValueName(String value) {
        return new JAXBElement<String>(_LdapWSEntryName_QNAME, String.class, LdapWSPairValue.class, value);
    }

}
